### ISSUE TITLE
Punch card

### ISSUE THREAD

**Issue by kiliankoe** [fsr/buerostatus#3]
Vielleicht nicht direkt Teil des Outputs, aber ich hätte gerne ein Diagramm ähnlich zu dem was GithHub als punch card ausgibt, voll cool.

<img width="953" alt="screen shot 2015-11-10 at 17 59 04" src="https://cloud.githubusercontent.com/assets/2625584/11069147/f088d8e2-87d4-11e5-8d50-3c6b5b2bcb7d.png">

Ne typische Woche von Anwesenheitszeiten im Semester, vorlesungsfreie Zeit. Oder Pro Monat. Was auch immer :smile: 

Vielleicht mit:
- https://github.com/jeyb/d3.punchcard
- https://github.com/fogleman/Punchcard

**Comment by kiliankoe** [comment]
Auch sehr cool ist die Seite vom [Bytewerk](http://stats.bytewerk.org).

<img width="728" alt="screen shot 2015-12-29 at 13 17 28" src="https://cloud.githubusercontent.com/assets/2625584/12034253/ce2d0bf8-ae2e-11e5-98a8-84aa43d11627.png">

**Comment by Feliix42** [comment]
Würde ich mir mal anschauen, wenn ich ohnehin einmal beim erstellen eines Graphen mit genau diesen Daten war. :smile: 

Aber warum muss das Script von **fogleman/Punchcard** in Python2 sein? Jetzt ist alles inkonsistent :disappointed: 
Ich schaue mal!

**Comment by kiliankoe** [comment]
Wuhu \o/

**Comment by dirkonet** [comment]
This is now handled in [a separate repo](https://github.com/fsr/stats) thanks to @Feliix42 :)
